name: 'Write variables to env file'
description: 'Configures environment variables for a workflow'
inputs:
  varFilePath:
    description: 'File path to variable file or directory. Defaults to ./.github/variables/* if none specified and runs against each file in that directory.'
    required: false
    default: ./.github/environment/main.env
runs:
  using: "composite"
  steps:
    - run: |
        sed "" $GITHUB_ENV >> ${{ inputs.varFilePath }}
      shell: bash
