name: add variable to environment/var file
on: workflow_dispatch
jobs:
  create:
    name: add new variable
    runs-on: ubuntu-latest
    env:
      FIRST: hello
      ENV_FILE: ./.github/environment/main.env
    steps:
      - name: Echo variable
        run: echo "${{ env.FIRST }}"
      - name: Echo action path
        run: echo "${{ github.action_path }}"
      - name: Echo path
        run: echo "${{ github.path }}"
      - name: Echo FURST
        run: echo "$FIRST"
      - name: Set variable to env file
        uses: ./.github/actions/write-to-env.yml
        
