name: add variable to environment/var file
on: workflow_dispatch
jobs:
  create:
    name: add new variable
    runs-on: ubuntu-latest
    env:
      - FIRST: hello
    steps:
      - name: Echo variable
        run: echo "{{ env.FIRST }}"
      - name: Echo action path
        run: echo "{{ github.action_path }}"
      - name: Echo path
        run: echo "{{ github.path }}"
