name: test environment secret
on: workflow_dispatch
env:
  FIRST_SECRET: ${{ secrets.FIRST_SECRET }}
  SECOND_SECRET: ${{ secrets.SECOND_SECRET }}
jobs:
  build:
    - name: test secret
      runs-on: ubuntu-latest
      steps:
        - name: Echo first secret
          run: echo "$FIRST_SECRET"
        - name: echo second secret
          run: echo "$SECOND_SECRET"
