name: test environment secret
on: workflow_dispatch
env:
  FIRST_SECRET: ${{ secrets.FIRST_SECRET }}
  SECOND_SECRET: ${{ secrets.SECOND_SECRET }}
jobs:
  build:
    name: test secret
    environment:
      name: Staging
    runs-on: ubuntu-latest
    steps:
      - name: Echo first secret
        run: if [ "$FIRST_SECRET" = "first" ]; then echo "correct"; fi;
      - name: echo second secret
        run: if [ "$SECOND_SECRET" = "second" ]; then echo "correct"; fi;
